package org.revature.revconnect.enums;
public enum NotificationType {
    CONNECTION_REQUEST,
    CONNECTION_ACCEPTED,
    NEW_FOLLOWER,
    LIKE,
    COMMENT,
    SHARE,
    COLLABORATION_INVITE,
    COLLABORATION_ACCEPTED,
    COLLABORATION_REJECTED,
    COLLABORATION_REVOKED,
    PROMOTION_GRANTED,
    PROMOTION_REVOKED
}
